defaults: &defaults
  adapter: postgresql
  host: localhost
  username: picsy
  password: picsy
  encoding: utf8

development:
  database: picsy_dev
  <<: *defaults

test:
  database: picsy_test
  <<: *defaults

production:
  database: picsy
  <<: *defaults
